import type { ReactNode } from "react";

export const metadata = {
  title: "Community Cares - How It Works",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
