export const metadata = {
  title: "Community Cares - Location",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
