import type { Metadata } from "next";
import { Montserrat, Shrikhand } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { MdOutlineHandshake } from "react-icons/md";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-paragraph",
  subsets: ["latin"],
});
const shrikhand = Shrikhand({
  weight: "400",
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Community Cares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${shrikhand.variable}`}>
        <header className="h-16 w-full bg-white justify-between items-center flex px-32">
          <div className="flex items-center gap-4">
            <MdOutlineHandshake size={40} color="" fill="#EE6A08" />
            <h1 className="text-2xl font-heading text-darkOrange">Community Cares</h1>
          </div>
          <nav>
            <ul className="flex items-center gap-8">
              <li>
                <a href="#" className="font-paragraph text-darkOrange text-base font-bold">About</a>
              </li>
              <li>
                <a href="#" className="font-paragraph text-darkOrange text-base font-bold">How It Works</a>
              </li>
              <li>
                <a href="#" className="font-paragraph text-darkOrange text-base font-bold">Testimonials</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
