import type { Metadata } from "next";
import { Montserrat, Shrikhand } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { MdOutlineHandshake } from "react-icons/md";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-paragraph",
  subsets: ["latin"],
});
const shrikhand = Shrikhand({
  weight: "400",
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Community Cares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${montserrat.variable} ${shrikhand.variable} h-full`}>
        <header className="h-16 w-full bg-white justify-center items-center flex px-4 sm:px-8 md:px-16 lg:px-32">
          <div className="flex items-center gap-2 sm:gap-4">
            <MdOutlineHandshake
              className="w-8 h-8 sm:w-10 sm:h-10"
              color=""
              fill="#EE6A08"
            />
            <h1 className="text-lg sm:text-xl md:text-2xl font-heading text-darkOrange">
              Community Cares
            </h1>
          </div>
          <nav className="hidden md:block">
            <ul className="flex items-center gap-4 lg:gap-8">
              <li>
                <a
                  href="#"
                  className="font-paragraph text-darkOrange text-sm lg:text-base font-bold"
                >
                  About
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="font-paragraph text-darkOrange text-sm lg:text-base font-bold"
                >
                  How It Works
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="font-paragraph text-darkOrange text-sm lg:text-base font-bold"
                >
                  Testimonials
                </a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
